"""add_import_run_promotion_counters

Revision ID: 1a7fb67e6eab
Revises: d6046cb1792a
Create Date: 2026-08-21 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '1a7fb67e6eab'
down_revision: Union[str, Sequence[str], None] = 'd6046cb1792a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: hand-written (see chat for why) — same reasoning as d6046cb1792a.
    # The check constraint is DROP + re-CREATE under its existing name
    # because Postgres has no ALTER CONSTRAINT for a CHECK's expression.
    op.add_column('import_runs', sa.Column('new_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('import_runs', sa.Column('updated_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('import_runs', sa.Column('deleted_jobs', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_constraint('import_runs_counts_check', 'import_runs', type_='check')
    op.create_check_constraint(
        'import_runs_counts_check',
        'import_runs',
        'records_received >= 0 AND records_staged >= 0 '
        'AND records_imported >= 0 AND records_rejected >= 0 '
        'AND new_jobs >= 0 AND updated_jobs >= 0 AND deleted_jobs >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('import_runs_counts_check', 'import_runs', type_='check')
    op.create_check_constraint(
        'import_runs_counts_check',
        'import_runs',
        'records_received >= 0 AND records_staged >= 0 '
        'AND records_imported >= 0 AND records_rejected >= 0',
    )
    op.drop_column('import_runs', 'deleted_jobs')
    op.drop_column('import_runs', 'updated_jobs')
    op.drop_column('import_runs', 'new_jobs')
    # ### end Alembic commands ###
