"""add job classification fields

Revision ID: 3f5573bab3f3
Revises: 7988b2cd5052
Create Date: 2026-08-24 03:50:09.536940

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f5573bab3f3"
down_revision: str | Sequence[str] | None = "7988b2cd5052"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("content_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "jobs", sa.Column("remote_status", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("remote_status_source", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "jobs", sa.Column("experience_level", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "jobs",
        sa.Column("experience_level_source", sa.String(length=20), nullable=True),
    )
    op.create_index(
        "jobs_experience_level_idx", "jobs", ["experience_level"], unique=False
    )
    op.create_index("jobs_remote_status_idx", "jobs", ["remote_status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("jobs_remote_status_idx", table_name="jobs")
    op.drop_index("jobs_experience_level_idx", table_name="jobs")
    op.drop_column("jobs", "experience_level_source")
    op.drop_column("jobs", "experience_level")
    op.drop_column("jobs", "remote_status_source")
    op.drop_column("jobs", "remote_status")
    op.drop_column("jobs", "content_updated_at")
    # ### end Alembic commands ###
