"""add composite filter indexes for keyset pagination

Revision ID: 3fbe4fe42552
Revises: ba3c63cabe99
Create Date: 2026-09-04 17:10:44.123808

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3fbe4fe42552"
down_revision: str | Sequence[str] | None = "ba3c63cabe99"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "jobs_active_classification_last_imported_at_id_idx",
        "jobs",
        [
            "is_active",
            "classification",
            sa.literal_column("last_imported_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "jobs_active_country_name_last_imported_at_id_idx",
        "jobs",
        [
            "is_active",
            "country_name",
            sa.literal_column("last_imported_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    op.create_index(
        "jobs_active_employment_type_last_imported_at_id_idx",
        "jobs",
        [
            "is_active",
            "employment_type",
            sa.literal_column("last_imported_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "jobs_active_employment_type_last_imported_at_id_idx", table_name="jobs"
    )
    op.drop_index("jobs_active_country_name_last_imported_at_id_idx", table_name="jobs")
    op.drop_index(
        "jobs_active_classification_last_imported_at_id_idx", table_name="jobs"
    )
    # ### end Alembic commands ###
