"""add inference fields to job staging

Revision ID: 4270f41a261e
Revises: 3f5573bab3f3
Create Date: 2026-08-24 04:59:04.977748

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4270f41a261e"
down_revision: str | Sequence[str] | None = "3f5573bab3f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_staging", sa.Column("remote_status", sa.String(length=30), nullable=True)
    )
    op.add_column(
        "job_staging",
        sa.Column("remote_status_source", sa.String(length=20), nullable=True),
    )
    op.add_column(
        "job_staging",
        sa.Column("experience_level", sa.String(length=30), nullable=True),
    )
    op.add_column(
        "job_staging",
        sa.Column("experience_level_source", sa.String(length=20), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_staging", "experience_level_source")
    op.drop_column("job_staging", "experience_level")
    op.drop_column("job_staging", "remote_status_source")
    op.drop_column("job_staging", "remote_status")
    # ### end Alembic commands ###
