"""drop unused source_job_url and affiliate_url columns

Revision ID: 439dff345b63
Revises: b3c91f4d27ae
Create Date: 2026-08-22 08:01:17.985526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439dff345b63'
down_revision: Union[str, Sequence[str], None] = 'b3c91f4d27ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'source_job_url')
    op.drop_column('jobs', 'affiliate_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('affiliate_url', sa.TEXT(), autoincrement=False, nullable=True, comment="Provider's affiliate destination URL, if supplied."))
    op.add_column('jobs', sa.Column('source_job_url', sa.TEXT(), autoincrement=False, nullable=True, comment="Provider's original job page URL, separate from apply_url."))
    # ### end Alembic commands ###
