"""add_import_run_field_fallback_warnings

Revision ID: 4fd7c8ec67e0
Revises: c27dd8e09f44
Create Date: 2026-08-21 05:55:14.657802

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4fd7c8ec67e0"
down_revision: str | Sequence[str] | None = "c27dd8e09f44"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "import_runs",
        sa.Column(
            "field_fallback_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Field names that required fallback handling, mapped to record counts.",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_runs", "field_fallback_warnings")
    # ### end Alembic commands ###
