"""initial_schema

Revision ID: 62526dc11097
Revises: 
Create Date: 2026-07-12 03:07:38.701621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62526dc11097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False, comment='Configured provider name; it is operational metadata, not an XML field.'),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('source_checksum', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_staged', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_imported', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('records_rejected', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'completed', 'failed')", name='import_runs_status_check'),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at', name='import_runs_completed_after_started_check'),
    sa.CheckConstraint('records_received >= 0 AND records_staged >= 0 AND records_imported >= 0 AND records_rejected >= 0', name='import_runs_counts_check'),
    sa.PrimaryKeyConstraint('id'),
    comment='One record per hourly Jobg8 feed import attempt.'
    )
    op.create_index('import_runs_status_created_at_idx', 'import_runs', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('job_staging',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('import_run_id', sa.BigInteger(), nullable=False),
    sa.Column('source_job_id', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete source record, including provider-only and future fields.'),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('advertiser_name', sa.Text(), nullable=True),
    sa.Column('advertiser_type', sa.Text(), nullable=True),
    sa.Column('display_reference', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_name', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Text(), nullable=True),
    sa.Column('start_date_text', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('work_hours', sa.Text(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_period', sa.Text(), nullable=True),
    sa.Column('salary_additional', sa.Text(), nullable=True),
    sa.Column('advertiser_logo_url', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=True),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('staged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(raw_payload) = 'object'", name='job_staging_payload_object_check'),
    sa.CheckConstraint("jsonb_typeof(validation_errors) = 'array'", name='job_staging_validation_errors_array_check'),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name='job_staging_salary_range_check'),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_run_id', 'source_job_id', name='job_staging_import_run_source_job_unique'),
    comment='Parsed records before promotion into the canonical jobs table.'
    )
    op.create_index('job_staging_import_run_valid_idx', 'job_staging', ['import_run_id', 'is_valid'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('source_job_id', sa.Text(), nullable=False, comment='Jobg8 SenderReference stored as the source-level job identity.'),
    sa.Column('advertiser_name', sa.Text(), nullable=True),
    sa.Column('advertiser_type', sa.Text(), nullable=True),
    sa.Column('display_reference', sa.Text(), nullable=True),
    sa.Column('classification', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('country_name', sa.Text(), nullable=True, comment='Feed country name; the source does not supply an ISO country code.'),
    sa.Column('location', sa.Text(), nullable=True, comment='Free-form feed location; may be Remote rather than a city.'),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('apply_url', sa.Text(), nullable=False),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Text(), nullable=True),
    sa.Column('start_date_text', sa.Text(), nullable=True),
    sa.Column('duration', sa.Text(), nullable=True),
    sa.Column('work_hours', sa.Text(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('salary_period', sa.Text(), nullable=True),
    sa.Column('salary_additional', sa.Text(), nullable=True),
    sa.Column('advertiser_logo_url', sa.Text(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=True),
    sa.Column('source_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.Text(), nullable=False),
    sa.Column('last_seen_import_run_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('first_imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("apply_url ~* '^https?://'", name='jobs_apply_url_http_check'),
    sa.CheckConstraint("btrim(description) <> ''", name='jobs_description_not_blank_check'),
    sa.CheckConstraint("btrim(title) <> ''", name='jobs_title_not_blank_check'),
    sa.CheckConstraint("jsonb_typeof(source_payload) = 'object'", name='jobs_source_payload_object_check'),
    sa.CheckConstraint('(is_active = true AND deactivated_at IS NULL) OR (is_active = false AND deactivated_at IS NOT NULL)', name='jobs_active_deactivated_consistency_check'),
    sa.CheckConstraint('last_imported_at >= first_imported_at', name='jobs_import_timestamps_check'),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name='jobs_salary_range_check'),
    sa.ForeignKeyConstraint(['last_seen_import_run_id'], ['import_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_name', 'source_job_id', name='jobs_source_identity_unique'),
    comment='Current canonical job catalogue from Jobg8 snapshots.'
    )
    op.create_index('jobs_active_classification_idx', 'jobs', ['classification'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('jobs_active_country_name_idx', 'jobs', ['country_name'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('jobs_last_seen_import_run_id_idx', 'jobs', ['last_seen_import_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('jobs_last_seen_import_run_id_idx', table_name='jobs')
    op.drop_index('jobs_active_country_name_idx', table_name='jobs', postgresql_where=sa.text('is_active = true'))
    op.drop_index('jobs_active_classification_idx', table_name='jobs', postgresql_where=sa.text('is_active = true'))
    op.drop_table('jobs')
    op.drop_index('job_staging_import_run_valid_idx', table_name='job_staging')
    op.drop_table('job_staging')
    op.drop_index('import_runs_status_created_at_idx', table_name='import_runs')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
