"""add admin audit logs

Revision ID: 7988b2cd5052
Revises: fccb299c93b2
Create Date: 2026-08-24 01:23:08.687455

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7988b2cd5052"
down_revision: str | Sequence[str] | None = "fccb299c93b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=False),
        sa.Column("target_id", sa.Text(), nullable=False),
        sa.Column(
            "before_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "after_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("ip_address", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"], ["admin_users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Administrator actions and their full before/after state.",
    )
    op.create_index(
        "admin_audit_logs_admin_user_id_idx",
        "admin_audit_logs",
        ["admin_user_id"],
        unique=False,
    )
    op.create_index(
        "admin_audit_logs_created_at_idx",
        "admin_audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "admin_audit_logs_target_type_target_id_idx",
        "admin_audit_logs",
        ["target_type", "target_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "admin_audit_logs_target_type_target_id_idx", table_name="admin_audit_logs"
    )
    op.drop_index("admin_audit_logs_created_at_idx", table_name="admin_audit_logs")
    op.drop_index("admin_audit_logs_admin_user_id_idx", table_name="admin_audit_logs")
    op.drop_table("admin_audit_logs")
    # ### end Alembic commands ###
