"""add auth foundation tables

Revision ID: ae7ed75aa030
Revises: e2d8894a6ffa
Create Date: 2026-08-22 04:52:00.398064

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

admin_role_enum = postgresql.ENUM("admin", "super_admin", name="admin_role_enum")
oauth_provider_enum = postgresql.ENUM("google", "apple", name="oauth_provider_enum")

# revision identifiers, used by Alembic.
revision: str = "ae7ed75aa030"
down_revision: str | Sequence[str] | None = "e2d8894a6ffa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "password_hash",
            sa.Text(),
            nullable=False,
            comment="Argon2 password hash; plaintext passwords are never stored.",
        ),
        sa.Column("role", admin_role_enum, nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="admin_users_email_unique"),
        comment="Password-authenticated administrative accounts.",
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("oauth_provider", oauth_provider_enum, nullable=False),
        sa.Column("oauth_subject_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "oauth_provider",
            "oauth_subject_id",
            name="users_oauth_identity_unique",
        ),
        comment="OAuth-authenticated job-seeker accounts.",
    )
    op.create_index("users_email_unique_idx", "users", ["email"], unique=True)
    op.create_table(
        "refresh_tokens",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column(
            "token_hash",
            sa.Text(),
            nullable=False,
            comment="One-way hash of the refresh token; never the raw token.",
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("admin_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(user_id IS NOT NULL AND admin_user_id IS NULL) "
            "OR (user_id IS NULL AND admin_user_id IS NOT NULL)",
            name="refresh_tokens_exactly_one_owner_check",
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"], ["admin_users.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        comment="Hashed refresh-token state; raw tokens are never stored.",
    )
    op.create_index(
        "refresh_tokens_admin_user_id_idx",
        "refresh_tokens",
        ["admin_user_id"],
        unique=False,
    )
    op.create_index(
        "refresh_tokens_expires_at_idx",
        "refresh_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        "refresh_tokens_token_hash_idx",
        "refresh_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        "refresh_tokens_user_id_idx",
        "refresh_tokens",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("refresh_tokens_user_id_idx", table_name="refresh_tokens")
    op.drop_index("refresh_tokens_token_hash_idx", table_name="refresh_tokens")
    op.drop_index("refresh_tokens_expires_at_idx", table_name="refresh_tokens")
    op.drop_index("refresh_tokens_admin_user_id_idx", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("users_email_unique_idx", table_name="users")
    op.drop_table("users")
    op.drop_table("admin_users")
    oauth_provider_enum.drop(op.get_bind(), checkfirst=True)
    admin_role_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
