"""add import run anomaly fields

Revision ID: ba3c63cabe99
Revises: 785f9d898131
Create Date: 2026-08-24 06:43:52.221151

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba3c63cabe99"
down_revision: str | Sequence[str] | None = "785f9d898131"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "import_runs",
        sa.Column(
            "is_anomalous",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.add_column(
        "import_runs",
        sa.Column(
            "anomaly_reasons",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("import_runs", "anomaly_reasons")
    op.drop_column("import_runs", "is_anomalous")
    # ### end Alembic commands ###
