"""add_import_run_unmapped_fields

Revision ID: c27dd8e09f44
Revises: 1a7fb67e6eab
Create Date: 2026-08-21 05:36:48.878503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c27dd8e09f44'
down_revision: Union[str, Sequence[str], None] = '1a7fb67e6eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_runs', sa.Column('unmapped_fields', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Unrecognized feed element names seen this run, mapped to occurrence counts.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_runs', 'unmapped_fields')
    # ### end Alembic commands ###
