"""add_provider_model_and_job_provider_columns

Revision ID: d6046cb1792a
Revises: 62526dc11097
Create Date: 2026-08-21 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6046cb1792a"
down_revision: str | Sequence[str] | None = "62526dc11097"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "providers",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "feed_url",
            sa.Text(),
            nullable=True,
            comment="SSRF validation happens at the application layer, not here.",
        ),
        sa.Column("format", sa.Text(), server_default=sa.text("'xml'"), nullable=False),
        sa.Column("archive_type", sa.Text(), nullable=True),
        sa.Column("schedule_cron", sa.Text(), nullable=True),
        sa.Column("timeout_seconds", sa.Integer(), nullable=True),
        sa.Column(
            "retry_max_attempts",
            sa.Integer(),
            server_default=sa.text("3"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Provider-specific settings and credential references only; never raw secrets.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Configured upstream job feed sources.",
    )

    # NOTE: hand-written, not machine-autogenerated (see chat for why). The
    # dev database for this project has no seed/migration history beyond
    # 62526dc11097 and no data-loading tooling wired up yet, so provider_id
    # is added directly as NOT NULL rather than the nullable -> backfill ->
    # NOT NULL two-step. If your dev/staging DB already has import_runs or
    # jobs rows, back those out before running this migration, or switch
    # this to the two-step approach.
    op.add_column(
        "import_runs", sa.Column("provider_id", sa.BigInteger(), nullable=False)
    )
    op.create_foreign_key(
        "import_runs_provider_id_fkey",
        "import_runs",
        "providers",
        ["provider_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    op.add_column("jobs", sa.Column("provider_id", sa.BigInteger(), nullable=False))
    op.add_column("jobs", sa.Column("slug", sa.Text(), nullable=False))
    op.add_column(
        "jobs",
        sa.Column(
            "source_job_url",
            sa.Text(),
            nullable=True,
            comment="Provider's original job page URL, separate from apply_url.",
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "affiliate_url",
            sa.Text(),
            nullable=True,
            comment="Provider's affiliate destination URL, if supplied.",
        ),
    )
    op.create_foreign_key(
        "jobs_provider_id_fkey",
        "jobs",
        "providers",
        ["provider_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint("jobs_slug_unique", "jobs", ["slug"])
    op.create_unique_constraint(
        "jobs_provider_source_job_unique", "jobs", ["provider_id", "source_job_id"]
    )
    op.create_index("jobs_provider_id_idx", "jobs", ["provider_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("jobs_provider_id_idx", table_name="jobs")
    op.drop_constraint("jobs_provider_source_job_unique", "jobs", type_="unique")
    op.drop_constraint("jobs_slug_unique", "jobs", type_="unique")
    op.drop_constraint("jobs_provider_id_fkey", "jobs", type_="foreignkey")
    op.drop_column("jobs", "affiliate_url")
    op.drop_column("jobs", "source_job_url")
    op.drop_column("jobs", "slug")
    op.drop_column("jobs", "provider_id")

    op.drop_constraint(
        "import_runs_provider_id_fkey", "import_runs", type_="foreignkey"
    )
    op.drop_column("import_runs", "provider_id")

    op.drop_table("providers")
    # ### end Alembic commands ###
