"""add deleted job retention hours

Revision ID: e2d8894a6ffa
Revises: f7e5da909a5e
Create Date: 2026-08-22 02:44:20.003929

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2d8894a6ffa"
down_revision: str | Sequence[str] | None = "f7e5da909a5e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column(
            "deleted_job_retention_hours",
            sa.Integer(),
            server_default=sa.text("12"),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        "providers_deleted_job_retention_positive_check",
        "providers",
        "deleted_job_retention_hours IS NULL OR deleted_job_retention_hours > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "providers_deleted_job_retention_positive_check",
        "providers",
        type_="check",
    )
    op.drop_column("providers", "deleted_job_retention_hours")
    # ### end Alembic commands ###
