"""add provider schedule interval minutes

Revision ID: f7e5da909a5e
Revises: 4fd7c8ec67e0
Create Date: 2026-08-22 02:11:49.860743

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7e5da909a5e"
down_revision: str | Sequence[str] | None = "4fd7c8ec67e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column("schedule_interval_minutes", sa.Integer(), nullable=True),
    )
    op.create_check_constraint(
        "providers_schedule_interval_positive_check",
        "providers",
        "schedule_interval_minutes IS NULL OR schedule_interval_minutes > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "providers_schedule_interval_positive_check", "providers", type_="check"
    )
    op.drop_column("providers", "schedule_interval_minutes")
    # ### end Alembic commands ###
